### ISSUE TITLE
allow for non pub methods

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/marine-rs-sdk#63]
```
#[marine]
pub struct XXXX {
    zzz: u32,
    pub aaa:String,
}
```

fails to compile.

why? I can than code type correct error pattern.

**Comment by mikevoronov** [comment]
`pub` is needed to allow macro generate code for serializing each field. In such code it's necessary to access a field of a struct. Non-pub methods could be done, but they would require getter in this case to allow macro accessing them.

Btw, why do you need this?

**Comment by dzmitry-lahoda** [comment]
> pub is needed to allow macro generate code for serializing each field
not sure why, if is not it is case for impl Serder for MyType? could make pub (mod) to work? or pub (crate)

> why do you need this?
implement rust result. so that in code all private methods are hidden. But can create Ok or Error by methods.

**Comment by mikevoronov** [comment]
> impl Serder for MyType

This `Serder` would also require `pub` access to field. But I have an another idea, and it's already partially implemented.
